CREATE TABLE `TB_USUARIO` (
	`ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
	`NOME` varchar(100) NOT NULL,
	`CPF` INT(11) NOT NULL UNIQUE,
	`DATA_NASCIMENTO` DATE NOT NULL,
	`TIPO` INT NOT NULL,
	`SENHA` VARCHAR(10) NOT NULL,
	`ID_ENDERECO` INT NOT NULL,
	`ID_POSTAGEM` INT NOT NULL,
	`ID_CONSULTA` INT NOT NULL,
	PRIMARY KEY (`ID_USUARIO`)
);

CREATE TABLE `TB_ENDERECO` (
	`ID_ENDERECO` INT NOT NULL AUTO_INCREMENT,
	`CEP` INT(8) NOT NULL,
	`Bairro` VARCHAR(20) NOT NULL,
	`RUA` VARCHAR(30) NOT NULL,
	`NUMERO` INT(10) NOT NULL,
	`COMPLEMENTO` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`ID_ENDERECO`)
);

CREATE TABLE `TB_POSTAGEM` (
	`ID_POSTAGEM` INT NOT NULL AUTO_INCREMENT,
	`DESCRICAO` varchar(500) NOT NULL,
	`DATA_POSTAGEM` DATETIME NOT NULL,
	`ID_TEMA` INT NOT NULL,
	PRIMARY KEY (`ID_POSTAGEM`)
);

CREATE TABLE `TB_TEMA` (
	`ID_TEMA` INT NOT NULL AUTO_INCREMENT,
	`ID_CARTEIRA` INT NOT NULL,
	`ID_EXAME` INT NOT NULL,
	`ID_CONSULTA` INT NOT NULL,
	`ID_SOBRE` INT(255) NOT NULL,
	`ID_CIRURGIA` INT NOT NULL,
	`ID_RECEITA` INT NOT NULL,
	PRIMARY KEY (`ID_TEMA`)
);

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `TB_USUARIO_fk0` FOREIGN KEY (`ID_ENDERECO`) REFERENCES `TB_ENDERECO`(`ID_ENDERECO`);

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `TB_USUARIO_fk1` FOREIGN KEY (`ID_POSTAGEM`) REFERENCES `TB_POSTAGEM`(`ID_POSTAGEM`);

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `TB_USUARIO_fk2` FOREIGN KEY (`ID_CONSULTA`) REFERENCES `TB_CONSULTA`(`ID_CONSULTA`);

ALTER TABLE `TB_POSTAGEM` ADD CONSTRAINT `TB_POSTAGEM_fk0` FOREIGN KEY (`ID_TEMA`) REFERENCES `TB_TEMA`(`ID_TEMA`);

